### PR TITLE
add apiversion, modify cmake & names

### PR DESCRIPTION
**Pull request by chincheta0815**
This PR includes the following:
- modified CMakeLists: making the build of the examples optional (default: on)
- add a function to validate the apiversion to have a mechanism check whether compatibility is met
- make the headers and names more hue'ish. this should make name more unique. Some names were general (MSG_* --> HUE_MSG_* or debug-h --> hue_debug.h)

### CODE REVIEW

**Comment by chincheta0815** [comment]
I hope every thing is on board now.

**Comment by daniel1111** [comment]
Yeah, it looks like everything's there now :)
But the examples no longer build for me, I should be able to sort that out, if you're ok with that?

**Comment by chincheta0815** [comment]
I am okay with that.
Say: When it‘s only due to CMakeLists.txt all other would be bad…

**Comment by daniel1111** [comment]
Thank you, that's now merged in :)

**Pull request merged**
